version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: python_env:v2
    container_name: fast-api
    ports:
      - "8000:8080"
    env_file:
      - ./.env
    volumes:
      - ./api:/app
    restart: unless-stopped
    depends_on:
      - db
    command: uvicorn app:app --host 0.0.0.0 --port 8080 --reload
volumes:
  postgres_data:

networks:
  default:
    name: api-network