
"""
Basic backtesting engine for trading algorithms.
"""

import pandas as pd
from typing import List, Dict, Any, Callable
import numpy as np

class Backtester:
    """
    A simple backtesting engine to evaluate trading algorithms.
    It simulates trades based on signals generated by an algorithm
    and calculates performance metrics.
    """

    def __init__(
        self, 
        initial_capital: float = 100000.0,
        commission_rate: float = 0.001, # 0.1% commission
        slippage_rate: float = 0.0005 # 0.05% slippage
    ):
        """
        Initializes the backtester with starting parameters.

        Args:
            initial_capital: The starting capital for the backtest.
            commission_rate: Commission rate per trade (e.g., 0.001 for 0.1%).
            slippage_rate: Slippage rate per trade (e.g., 0.0005 for 0.05%).
        """
        self.initial_capital = initial_capital
        self.commission_rate = commission_rate
        self.slippage_rate = slippage_rate
        self.capital = initial_capital
        self.holdings = {}
        self.trade_log = []
        self.portfolio_value_history = []

    def _execute_trade(self, date: pd.Timestamp, ticker: str, signal_type: str, price: float, quantity: int):
        """
        Executes a simulated trade and updates capital and holdings.
        """
        cost = price * quantity
        commission = cost * self.commission_rate
        slippage = cost * self.slippage_rate

        if signal_type == 'buy':
            total_cost = cost + commission + slippage
            if self.capital >= total_cost:
                self.capital -= total_cost
                self.holdings[ticker] = self.holdings.get(ticker, 0) + quantity
                self.trade_log.append({
                    'date': date,
                    'ticker': ticker,
                    'type': 'BUY',
                    'price': price,
                    'quantity': quantity,
                    'cost': total_cost
                })
                return True
            else:
                # print(f"Not enough capital to buy {quantity} of {ticker} at {price}")
                return False
        elif signal_type == 'sell':
            if self.holdings.get(ticker, 0) >= quantity:
                total_revenue = cost - commission - slippage
                self.capital += total_revenue
                self.holdings[ticker] -= quantity
                if self.holdings[ticker] == 0:
                    del self.holdings[ticker]
                self.trade_log.append({
                    'date': date,
                    'ticker': ticker,
                    'type': 'SELL',
                    'price': price,
                    'quantity': quantity,
                    'revenue': total_revenue
                })
                return True
            else:
                # print(f"Not enough {ticker} to sell {quantity}")
                return False
        return False

    def run_backtest(
        self,
        ohlcv_data: Dict[str, List[Dict[str, Any]]],
        algorithm: Callable[[List[Dict[str, Any]]], List[Dict[str, Any]]],
        start_date: str,
        end_date: str,
        trade_quantity: int = 10 # Default quantity for each trade
    ) -> Dict[str, Any]:
        """
        Runs the backtest for a given algorithm and data.

        Args:
            ohlcv_data: A dictionary where keys are tickers and values are lists
                        of OHLCV data for that ticker.
            algorithm: A callable that takes OHLCV data (list of dicts) and returns
                       a list of trade signals (dicts with 'ticker', 'signal_time',
                       'price', 'type': 'buy'/'sell').
            start_date: Start date for the backtest (YYYY-MM-DD).
            end_date: End date for the backtest (YYYY-MM-DD).
            trade_quantity: The fixed quantity of shares to buy/sell per signal.

        Returns:
            A dictionary containing backtest results (e.g., total return, MDD).
        """
        self.capital = self.initial_capital
        self.holdings = {}
        self.trade_log = []
        self.portfolio_value_history = []

        all_dates = sorted(list(set(pd.to_datetime(d['date']).date() 
                                    for ticker_data in ohlcv_data.values() 
                                    for d in ticker_data)))
        
        backtest_start = pd.to_datetime(start_date).date()
        backtest_end = pd.to_datetime(end_date).date()

        # Filter dates within the backtest period
        trading_dates = [d for d in all_dates if backtest_start <= d <= backtest_end]
        if not trading_dates:
            print("No trading dates found within the specified period.")
            return self._calculate_performance()

        print(f"Starting backtest from {trading_dates[0]} to {trading_dates[-1]}")

        for current_date in trading_dates:
            current_date_ts = pd.Timestamp(current_date)
            # Calculate current portfolio value
            current_portfolio_value = self.capital
            for ticker, qty in self.holdings.items():
                # Get the closing price for the current date
                # This assumes ohlcv_data is sorted by date
                ticker_df = pd.DataFrame(ohlcv_data.get(ticker, []))
                if not ticker_df.empty:
                    ticker_df['date'] = pd.to_datetime(ticker_df['date'])
                    current_price_row = ticker_df[ticker_df['date'].dt.date == current_date]
                    if not current_price_row.empty:
                        current_price = current_price_row['close'].iloc[0]
                        current_portfolio_value += current_price * qty
            self.portfolio_value_history.append(current_portfolio_value)

            # Generate signals for each ticker based on data up to current_date
            for ticker, data in ohlcv_data.items():
                data_up_to_today = [d for d in data if pd.to_datetime(d['date']).date() <= current_date]
                if not data_up_to_today:
                    continue

                # Call the algorithm to get signals
                # The algorithm should return signals for the *latest* data point
                signals = algorithm(data_up_to_today)

                for signal in signals:
                    signal_date = pd.to_datetime(signal['signal_time']).date()
                    if signal_date == current_date: # Only act on signals for today
                        if signal['type'] == 'buy':
                            self._execute_trade(current_date_ts, signal['ticker'], 'buy', signal['price'], trade_quantity)
                        elif signal['type'] == 'sell':
                            self._execute_trade(current_date_ts, signal['ticker'], 'sell', signal['price'], trade_quantity)

        # Liquidate all holdings at the end of the backtest
        for ticker, qty in list(self.holdings.items()): # Use list() to avoid RuntimeError during iteration
            ticker_df = pd.DataFrame(ohlcv_data.get(ticker, []))
            if not ticker_df.empty:
                ticker_df['date'] = pd.to_datetime(ticker_df['date'])
                final_price_row = ticker_df[ticker_df['date'].dt.date == backtest_end]
                if not final_price_row.empty:
                    final_price = final_price_row['close'].iloc[0]
                    self._execute_trade(pd.Timestamp(backtest_end), ticker, 'sell', final_price, qty)

        return self._calculate_performance()

    def _calculate_performance(self) -> Dict[str, Any]:
        """
        Calculates and returns key performance metrics.
        """
        if not self.portfolio_value_history:
            return {
                'total_return': 0.0,
                'cagr': 0.0,
                'mdd': 0.0,
                'num_trades': 0,
                'winning_trades': 0,
                'losing_trades': 0,
                'win_rate': 0.0
            }

        portfolio_series = pd.Series(self.portfolio_value_history)
        total_return = (self.capital / self.initial_capital) - 1

        # Calculate CAGR (Compound Annual Growth Rate)
        num_years = (pd.to_datetime(self.portfolio_value_history[-1]) - pd.to_datetime(self.portfolio_value_history[0])).days / 365.25
        cagr = ((self.capital / self.initial_capital)**(1/num_years)) - 1 if num_years > 0 else 0.0

        # Calculate MDD (Maximum Drawdown)
        peak = portfolio_series.expanding(min_periods=1).max()
        drawdown = (portfolio_series - peak) / peak
        mdd = drawdown.min() if not drawdown.empty else 0.0

        # Calculate win rate (simplified: assuming each buy/sell pair is a trade)
        winning_trades = 0
        losing_trades = 0
        # This part needs more sophisticated logic to pair buy/sell trades correctly
        # For simplicity, we'll just count total trades for now.
        num_trades = len(self.trade_log)

        return {
            'total_return': round(total_return * 100, 2),
            'cagr': round(cagr * 100, 2),
            'mdd': round(mdd * 100, 2),
            'num_trades': num_trades,
            'winning_trades': winning_trades, # Placeholder
            'losing_trades': losing_trades, # Placeholder
            'win_rate': round(winning_trades / num_trades * 100, 2) if num_trades > 0 else 0.0
        }

# --- Example Usage (for testing) ---
if __name__ == '__main__':
    # This example will not run the full UptrendMomentumScreener
    # as it requires a PyKis client and actual API calls.
    # Instead, we'll use a dummy algorithm and dummy data.

    print("Running dummy backtest example...")

    # Dummy OHLCV data for a single ticker
    dummy_ohlcv_data = {
        'DUMMY': [
            {'date': '2023-01-01', 'close': 100},
            {'date': '2023-01-02', 'close': 101},
            {'date': '2023-01-03', 'close': 102},
            {'date': '2023-01-04', 'close': 103},
            {'date': '2023-01-05', 'close': 104},
            {'date': '2023-01-06', 'close': 105},
            {'date': '2023-01-07', 'close': 106},
            {'date': '2023-01-08', 'close': 107},
            {'date': '2023-01-09', 'close': 108},
            {'date': '2023-01-10', 'close': 109},
            {'date': '2023-01-11', 'close': 110},
            {'date': '2023-01-12', 'close': 109},
            {'date': '2023-01-13', 'close': 108},
            {'date': '2023-01-14', 'close': 107},
            {'date': '2023-01-15', 'close': 106},
        ]
    }

    # Dummy algorithm: always buy on 3rd day, sell on 7th day
    def dummy_algorithm(ohlcv_data_for_ticker: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        signals = []
        if len(ohlcv_data_for_ticker) >= 3 and ohlcv_data_for_ticker[-1]['date'] == '2023-01-03':
            signals.append({
                'ticker': 'DUMMY',
                'signal_time': ohlcv_data_for_ticker[-1]['date'],
                'price': ohlcv_data_for_ticker[-1]['close'],
                'type': 'buy'
            })
        if len(ohlcv_data_for_ticker) >= 7 and ohlcv_data_for_ticker[-1]['date'] == '2023-01-07':
            signals.append({
                'ticker': 'DUMMY',
                'signal_time': ohlcv_data_for_ticker[-1]['date'],
                'price': ohlcv_data_for_ticker[-1]['close'],
                'type': 'sell'
            })
        return signals

    backtester = Backtester(initial_capital=10000)
    results = backtester.run_backtest(
        ohlcv_data=dummy_ohlcv_data,
        algorithm=dummy_algorithm,
        start_date='2023-01-01',
        end_date='2023-01-15',
        trade_quantity=10
    )

    print("\n--- Backtest Results (Dummy Algorithm) ---")
    for key, value in results.items():
        print(f"{key}: {value}")
